version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - VERSION=1.0.0
      - FLASK_APP=app:create_app
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
