name: Multi Environment CI/CD Pipeline

on:
    push:
        branches: [staging]
    pull_request:
        branches: [main, staging]

env:
    IMAGE_NAME: flask-ci-cd-app
    AWS_EC2_STAGING_HOST: ${{ secrets.AWS_EC2_STAGING_HOST }}
    AWS_EC2_PRDUCTION_HOST: ${{ secrets.AWS_EC2_PRDUCTION_HOST }}
    AWS_EC2_USER: ubuntu

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest

            - name: Run tests
              run: |
                  pytest -v tests/

    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'

        strategy:
            matrix:
                include:
                    - branch: main
                      environment: production
                      tag: production
                    - branch: staging
                      environment: staging
                      tag: staging

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

            - name: Set environment info
              run: |
                  echo "DOCKER_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_ENV
                  echo "IMAGE_BUILD_TIME=$(date -u)" >> $GITHUB_ENV

    deploy-staging:
        needs: build-and-push
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging'
        environment: staging

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Staging EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.AWS_EC2_STAGING_HOST }}
                  username: ${{ env.AWS_EC2_USER }}
                  key: ${{ secrets.AWS_EC2_SSH_KEY }}
                  script: |
                      cd /opt/app
                      echo "🚀 Deploying to STAGING environment..."
                      echo "📦 Pulling latest Docker image from Docker Hub..."

                      # Login to Docker Hub
                      echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

                      # Pull the latest image
                      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

                      # Stop and remove existing containers
                      docker-compose down

                      # Start new containers with the latest image
                      docker-compose up -d

                      # Clean up old images
                      docker image prune -f

                      echo "✅ Staging deployment completed successfully!"
                      echo "🕒 Image built at: ${{ env.IMAGE_BUILD_TIME }}"

                      # Show running containers
                      echo "📊 Current containers:"
                      docker-compose ps

                      # Health check
                      echo "🔍 Performing health check..."
                      sleep 10
                      curl -f http://localhost:5000/health || exit 1
                      echo "✅ Health check passed!"

    deploy-production:
        needs: build-and-push
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Production EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.AWS_EC2_PRDUCTION_HOST }}
                  username: ${{ env.AWS_EC2_USER }}
                  key: ${{ secrets.AWS_EC2_SSH_KEY }}
                  script: |
                      cd /opt/app
                      echo "Deploying to PRODUCTION environment..."
                      if [ ! -d ".git" ]; then
                          echo "Cloning the repository into /opt/app..."
                          git clone https://github.com/PhilipOyelegbin/automated-flaskapp-deployment.git .
                      fi
                      echo "Fetching latest changes..."
                      git fetch origin main
                      git checkout main
                      git pull origin main
                      docker-compose down
                      docker-compose pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${DOCKER_IMAGE_TAG}
                      docker-compose up -d
                      echo "Production deployment completed successfully!"

    notify:
        needs: [test, build-and-push, deploy-staging, deploy-production]
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Post Slack Notification
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  payload: |
                      {
                          "text": "GitHub Actions CI/CD Notification",
                          "blocks": [
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "🚀 Deployment ${{ job.status }} ${{github.base_ref}}\nJob: notify\nStatus: ${{ job.status }}\nBranch: ${{ github.ref_name }}/${{github.event_name}}\nCommit: ${{ github.sha }}\nURL: ${{github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                                  }
                              }
                          ]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
