name: Multi-Environment CI/CD Pipeline

on:
    push:
        branches: [staging]
    pull_request:
        branches: [main, staging]

env:
    IMAGE_NAME: flask-ci-cd-app
    AWS_EC2_STAGING_HOST: ${{ secrets.AWS_EC2_STAGING_HOST }}
    AWS_EC2_PRDUCTION_HOST: ${{ secrets.AWS_EC2_PRDUCTION_HOST }}
    AWS_EC2_USER: ubuntu

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pytest

            - name: Run tests
              run: |
                  pytest -v tests/

    build-and-push:
        needs: test
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'

        strategy:
            matrix:
                include:
                    - branch: main
                      environment: production
                      tag: production
                    - branch: staging
                      environment: staging
                      tag: staging

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Extract metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=ref,event=branch
                      type=sha,prefix={{branch}}-
                      type=raw,value=latest,enable={{is_default_branch}}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    deploy-staging:
        needs: build-and-push
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/staging'
        environment: staging

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.AWS_EC2_STAGING_HOST }}
                  username: ${{ env.AWS_EC2_USER }}
                  key: ${{ secrets.AWS_EC2_SSH_KEY }}
                  script: |
                      cd /opt/app
                      echo "Deploying to STAGING environment..."
                      git init
                      git remote add origin https://github.com/PhilipOyelegbin/automated-flaskapp-deployment.git
                      git pull origin staging
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d
                      echo "Staging deployment completed successfully!"

    deploy-production:
        needs: build-and-push
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        environment: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy to Production EC2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.AWS_EC2_PRDUCTION_HOST }}
                  username: ${{ env.AWS_EC2_USER }}
                  key: ${{ secrets.AWS_EC2_SSH_KEY }}
                  script: |
                      cd /opt/app
                      echo "Deploying to PRODUCTION environment..."
                      git init
                      git remote add origin https://github.com/PhilipOyelegbin/automated-flaskapp-deployment.git
                      git pull origin main
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d
                      echo "Production deployment completed successfully!"

    notify:
        needs: [test, build-and-push, deploy-staging, deploy-production]
        runs-on: ubuntu-latest
        if: always()

        steps:
            - name: Post Slack Notification
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  payload: |
                      {
                          "text": "GitHub Actions CI/CD Notification",
                          "blocks": [
                              {
                                  "type": "section",
                                  "status": "success",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "🚀 Staging Deployment success\nJob: notify\nStatus: success\nBranch: 8/merge\nCommit: 2bd90e1e098cd6b81bff30530506f6509910a52e\nURL: https://github.com/PhilipOyelegbin/automated-flaskapp-deployment/actions/runs/18522497326"
                                  }
                              }
                          ]
                      }
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                  SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
